name: CandyGuideNPC
version: 'v1.0'
main: com.heliosay.candyGuideNPC.CandyGuideNPC
api-version: '1.21'
author: HeliosAy
description: Yeni oyunculara rehberlik yapan NPC plugin sistemi
depend:
  - Citizens
softdepend: [NoteBlockAPI]

commands:
  guidenpc:
    description: Ana GuideNPC komutu
    usage: /<command> <sub>
    aliases: [gnpc]
